/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JLabel;

/**
 *
 * @author lucasbloise
 */
public class PuntajeVista extends javax.swing.JFrame {

    public JLabel getTiempoDePartida() {
        return tiempoDePartida;
    }

    public JLabel getPlayer1BarcosHundidos() {
        return player1BarcosHundidos;
    }

    public JLabel getPlayer1Disparos() {
        return player1Disparos;
    }

    public JLabel getPlayer1DisparosAgua() {
        return player1DisparosAgua;
    }

    public JLabel getPlayer1DisparosRepetidos() {
        return player1DisparosRepetidos;
    }

    public JLabel getPlayer1Name() {
        return player1Name;
    }

    public JLabel getPlayer2BarcosHundidos() {
        return player2BarcosHundidos;
    }

    public JLabel getPlayer2Disparos() {
        return player2Disparos;
    }

    public JLabel getPlayer2DisparosAgua() {
        return player2DisparosAgua;
    }

    public JLabel getPlayer2DisparosRepetidos() {
        return player2DisparosRepetidos;
    }

    public JLabel getPlayer2Name() {
        return player2Name;
    }

    /**
     * Creates new form PuntajeVista
     */
    public PuntajeVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        player1Name = new javax.swing.JLabel();
        player2Name = new javax.swing.JLabel();
        player1Disparos = new javax.swing.JLabel();
        player1BarcosHundidos = new javax.swing.JLabel();
        player1DisparosAgua = new javax.swing.JLabel();
        player1DisparosRepetidos = new javax.swing.JLabel();
        player2Disparos = new javax.swing.JLabel();
        player2BarcosHundidos = new javax.swing.JLabel();
        player2DisparosAgua = new javax.swing.JLabel();
        player2DisparosRepetidos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tiempoDePartida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        player1Name.setText("Jugador 1");

        player2Name.setText("Jugador 2");

        player1Disparos.setText("Disparos: 0");

        player1BarcosHundidos.setText("Barcos Hundidos: 0");

        player1DisparosAgua.setText("Disparos al Agua: 0");

        player1DisparosRepetidos.setText("Disparos Repetidos: 0");

        player2Disparos.setText("Disparos: 0");

        player2BarcosHundidos.setText("Barcos Hundidos: 0");

        player2DisparosAgua.setText("Disparos al Agua: 0");

        player2DisparosRepetidos.setText("Disparos Repetidos: 0");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Puntajes");

        tiempoDePartida.setText("Tiempo de Partida:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tiempoDePartida)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(player1Name)
                        .addComponent(player1Disparos)
                        .addComponent(player1DisparosRepetidos)
                        .addComponent(player1DisparosAgua)
                        .addComponent(player1BarcosHundidos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player2Name)
                    .addComponent(player2Disparos)
                    .addComponent(player2DisparosRepetidos)
                    .addComponent(player2DisparosAgua)
                    .addComponent(player2BarcosHundidos))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1Name)
                    .addComponent(player2Name))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(player1Disparos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(player1BarcosHundidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(player1DisparosAgua)
                        .addGap(18, 18, 18)
                        .addComponent(player1DisparosRepetidos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(player2Disparos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(player2BarcosHundidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(player2DisparosAgua)
                        .addGap(18, 18, 18)
                        .addComponent(player2DisparosRepetidos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(tiempoDePartida)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel player1BarcosHundidos;
    private javax.swing.JLabel player1Disparos;
    private javax.swing.JLabel player1DisparosAgua;
    private javax.swing.JLabel player1DisparosRepetidos;
    private javax.swing.JLabel player1Name;
    private javax.swing.JLabel player2BarcosHundidos;
    private javax.swing.JLabel player2Disparos;
    private javax.swing.JLabel player2DisparosAgua;
    private javax.swing.JLabel player2DisparosRepetidos;
    private javax.swing.JLabel player2Name;
    private javax.swing.JLabel tiempoDePartida;
    // End of variables declaration//GEN-END:variables
}
